### ISSUE TITLE
Feature Flag payloads does not work

### ISSUE THREAD

**Issue by benjackwhite** [PostHog/posthog-ios#49]
## Problem
Feature Flag payloads are returned as a string and the expectation is that we JSON parse the value into the primitive type ([see posthog-js](https://github.com/PostHog/posthog-js/blob/master/src/posthog-core.ts#L1092).

Our tests incorrectly assume the response type is pre-parsed (although one could argue that would be the expectation I would have of the API - that's a separate discussion...)

## Proposed solution
- Change the tests so that the payload is a json encoded string
- Fix the logic to first parse the json before casting

**Comment by EDsCODE** [comment]
Ohh, are you referring to these [calls](https://github.com/PostHog/posthog-ios/blob/master/PostHog/Classes/PHGPostHog.m#L337) that assume it's returning an object/dict?

**Comment by marandaneto** [comment]
@benjackwhite [here](https://github.com/PostHog/posthog-js/blob/a1307003da7354ea0a09a4093060b449225b92ce/src/posthog-core.ts#L1134C20-L1134C30) do you mean?
If this is still an issue, probably the new Android SDK has to be fixed as well.
I always see a JSON structure being returned and not a stringified JSON, maybe it's fixed in v3?
@neilkakkar can chime in as well.

**Comment by marandaneto** [comment]
Closed because of the new major version that should have addressed this use case
https://github.com/PostHog/posthog-ios/pull/75
